name: Smoke Checks

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'

  workflow_dispatch:
    inputs:
      record_snapshots:
        description: 'Record snapshots on CI?'
        type: boolean
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1 # Disable cleanup for homebrew, we don't need it on CI
  IOS_SIMULATOR_DEVICE: "iPhone 16 Pro (18.5)"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_PR_NUM: ${{ github.event.pull_request.number }}

jobs:
  test-llc:
    name: Test LLC
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
    - uses: ./.github/actions/bootstrap
      env:
        INSTALL_YEETD: true
        INSTALL_SONAR: true
    - name: Run LLC Tests (Debug)
      run: bundle exec fastlane test device:"${{ env.IOS_SIMULATOR_DEVICE }}"
      timeout-minutes: 40
    - name: Run Sonar analysis
      run: bundle exec fastlane sonar_upload
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: "You shall not pass!"
        job_name: "Test LLC (Debug)"
        fields: repo,commit,author,workflow
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: ${{ github.event_name == 'push' && failure() }}
    - name: Parse xcresult
      if: failure()
      run: |
        brew install chargepoint/xcparse/xcparse
        xcparse logs fastlane/test_output/StreamVideo.xcresult fastlane/test_output/logs/
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: Test Data LLC
        path: |
          fastlane/test_output/logs/*/Diagnostics/**/*.txt
          fastlane/test_output/logs/*/Diagnostics/simctl_diagnostics/DiagnosticReports/*
    - name: Upload Test Coverage
      uses: actions/upload-artifact@v4
      with:
        name: test-coverage-${{ github.event.pull_request.number }}
        path: reports/sonarqube-generic-coverage.xml

  automated-code-review:
    name: Automated Code Review
    runs-on: macos-15
    env:
      XCODE_VERSION: "16.0"
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: ./.github/actions/bootstrap
    - run: bundle exec fastlane lint_pr
    - run: bundle exec fastlane rubocop
    - run: bundle exec fastlane run_swift_format strict:true

  build-apps:
    name: Build Demo App
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: ./.github/actions/ruby-cache
    - uses: ./.github/actions/xcode-cache
    - name: Build Demo App
      run: bundle exec fastlane build_demo
